# fly.toml app configuration file generated for price-tracker-be on 2024-03-29T18:22:10+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'price-tracker-be'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
